### ISSUE TITLE
OATH Functionality Missing

### ISSUE THREAD

**Issue by camkorth24** [Yubico/yubioath-android#126]
Whether I plug the Security Key NFC inyo USB or NFC it will not read in my Galaxy Note 20. It says OATH functionality is missing or error in YubiKey communication yet it works on a laptop and iOS.

**Comment by dainnilsson** [comment]
The [Security Key NFC](https://www.yubico.com/us/product/security-key-nfc-by-yubico/) indeed does not support the OATH protocol. When you say it works on a laptop and iOS, are you referring to WebAuthn/FIDO working? Because the Yubico Authenticator apps on those platforms should not work there either.

**Comment by camkorth24** [comment]
Well that's unfortunate. What let's would best on cross platform including Android, iOS, OSX, Windows 10? The Authenticator works on my iPhone but nothing else. I'm able to use it on a webauth and TOTP.

**Comment by dainnilsson** [comment]
Are you sure you have the Security Key NFC (a blue key)? Because TOTP should not work on that, on any platform.

**Comment by camkorth24** [comment]
I mean yes I'm looking right at it. However, I absolutely could be using the wrong term here, this is not an area of expertise for me and support has been all hit helpful. Over 14 days lockout and messaging the support since I can't get a replace the key that works.

**Comment by camkorth24** [comment]
![Uploading 96260395...]

**Comment by camkorth24** [comment]
![image](https://user-images.githubusercontent.com/69029268/96260463-469d3000-0f7c-11eb-8e4e-19d102f12a97.jpeg)

**Comment by camkorth24** [comment]
So what is it using if not TOTP? And what keys are gonna best suit the cross platform?

**Comment by dainnilsson** [comment]
That definitely looks like a Security Key NFC to me.
TOTP (OATH-TOTP) is the usually 6 digit codes which refresh every 30 seconds. If you're getting those from that key, then I'm not sure what's going on.

The Security Key is used for WebAuthn/FIDO, which is supported cross platform, and is supported on a growing number of sites. It doesn't require any typing of OTPs, and has better protections than OTP-based protocols. This requires a supported browser instead of a separate companion app (so no Yubico Authenticator needed). You can read more about it here: https://www.yubico.com/authentication-standards/webauthn/

**Comment by camkorth24** [comment]
Then which key is gonna support all my 250+ OTP and TOTP that don't have any other support for Fido or webauth?

**Comment by dainnilsson** [comment]
The YubiKey 5 series keys have support for OATH-TOTP in addition to WebAuthn, but the number of credentials that can be stored is limited to 32 per YubiKey. If you have 250+ TOTP credentials then there's no YubiKey which will be able to store them all. You may be able to store them in a password manager with support for TOTP and YubiKey, but I'm afraid I can't help you with any recommendations there.

**Comment by camkorth24** [comment]
Thank you, I appreciate it. Does the standard Security Key work on android as well?

**Comment by dainnilsson** [comment]
Yes, Android is supported.
