### ISSUE TITLE
Error in communication 

### ISSUE THREAD

**Issue by stefanelul2000** [Yubico/yubioath-android#127]
I know this is an issue that had been raised before but I've just got my key which is a YubiKey 5 NFC I have setup Facebook for TOTP but I can't seem to be able to read it via NFC with my Galaxy note 10+. Meanwhile I have tried with an iPhone and it's respective app and it works without any problems. What can in do in this case ?

**Comment by aspenbaily** [comment]
I believe the issue here is that since Android 11 was released, there was an overhaul of the permission manager.

Because both the F-Droid and the Play store releases haven't been updated in over a year, there's no prompt to ask for device permissions (like NFC, camera for reading QR codes, and storage permissions).  You can have NFC enabled, toggle all of the app's settings, and still get an error message saying that the device can't be read, because your phone hasn't given permission to the device to actually read from NFC.  Even when you go to plug it in, none of the keys are stored because the app doesn't have storage permissions.  There's no toggle in the permission manager because the developers were writing the app with the expectation that these permissions would be enabled by default, as was the past system for Android permissions.

**Comment by florianajir** [comment]
> I believe the issue here is that since Android 11 was released, there was an overhaul of the permission manager.
> 
> Because both the F-Droid and the Play store releases haven't been updated in over a year, there's no prompt to ask for device permissions (like NFC, camera for reading QR codes, and storage permissions). You can have NFC enabled, toggle all of the app's settings, and still get an error message saying that the device can't be read, because your phone hasn't given permission to the device to actually read from NFC. Even when you go to plug it in, none of the keys are stored because the app doesn't have storage permissions. There's no toggle in the permission manager because the developers were writing the app with the expectation that these permissions would be enabled by default, as was the past system for Android permissions.

did you figured out a workaround ?

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter. We have also released a new version of the app, please let us know in the new repository if the issues with connectivity are still present.
