### ISSUE TITLE
Yubikey 5C Nano not working on Samsung S7

### ISSUE THREAD

**Issue by Elliander** [Yubico/yubioath-android#132]
Since the Yubikey 5C Nano isn't working in Chromebook's Android Layer I purchased a USB-C to micro USB dongle to plug it into my Samsung S7. It doesn't work there either. In fact, unlike in the Chromebook, the lights don't even turn on there! 

Is there **_ANY_** device that this key will work in?

**EDIT:** I know it's not the adapter or the key, because when I plug it into my PC the Yubico Authenticator for PC does recognize the key (finally) but I'd rather not rely on windows for the Authentication since it's the most likely to be compromised device I have.

**Comment by dainnilsson** [comment]
This is likely due to the adapter not being a so-called "On-the-Go" adapter. For USB devices prior to USB-C, a special cable is needed to indicate to the phone that it should act as a host and not as a peripheral (for USB-C the same connector is used in both cases, and negotiation is done by the devices themselves).

The USB-C specification states that legacy adapters (i.e. adapters with a USB-A or USB-B plug) with a USB-C receptacle are "not defined or allowed" because they can create "many invalid and potentially unsafe" cable combinations. Any such adapters are thus "non-standard" and we can't make any assurances that they will work.

**Comment by Elliander** [comment]
So if it is an OTG adapter it should work? and if it isn't it shouldn't?

If I setup Yubico Authenticator on PC will the same key work on Android if I get an OTG adapter for the key?

**Comment by Elliander** [comment]
Ugh. Having to use two different devices to authenticate seems impossible with this key. I put all the information in correctly on windows, but the time based 2FA fails every time. I make sure that the time is correct on both devices, but I can't see if they are on exactly the same second. I've been trying to get anything to work for days and I just can't seem to.

**Comment by dainnilsson** [comment]
> So if it is an OTG adapter it should work? and if it isn't it shouldn't?

If it isn't an OTG adapter then it definitely wont't work, as the phone will be in peripheral mode. If it is an OTG adapter, then it _might_ work. A USB-A YubiKey works via USB-OTG with an Android phone that has a Micro-USB port. However, since this is a USB-C YubiKey, and that requires an adapter that is disallowed by the USB-C specification, I can't say for sure if it will or won't work. Probably yes, but it's "unsupported".

> If I setup Yubico Authenticator on PC will the same key work on Android if I get an OTG adapter for the key?

Given the same caveats as above, assuming the YubiKey itself works correctly on the Android device, then yes, the same YubiKey should work both on PC and phone, with the same credentials.

The clock on the host (PC or Phone) needs to be accurate for the correct code to be generated. Normally, a code is valid for a 30-second period, so if it's off by a few seconds this won't matter. Most servers will allows some tolerance here too.

I typically find it easier to use a demo TOTP service to troubleshoot these types of issues, like for example: https://totp.danhersam.com/ - By adding a credential generated from there, you can compare the code being output by the YubiKey to the correct value.

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter. We have released a new version of the app, please verify that your issue is present and eventually open a new issue in the new repository.
