### ISSUE TITLE
"Error in Yubikey Communication" in both my primary and backup keys

### ISSUE THREAD

**Issue by aldenstpage** [Yubico/yubioath-android#133]
I'm using a Samsung Galaxy S9 on Android 10. I have been using Yubico Authenticator successfully for two years, but now, all of sudden, I can't access my OTPs using my primary or backup Yubikey 5 NFC. Pressing either key gives me "error in yubikey communication". Both keys work fine on my desktop through USB.

So far, I've tried toggling all of the NFC options and pressing my keys again, but I haven't had any luck.

I reached out to Yubico support but didn't hear anything back. Any help would be appreciated!

**Comment by aldenstpage** [comment]
Somehow, the application got in a corrupt state. After reinstalling the app, I'm able to use NFC again. I have a hunch that a security update that went out in April is responsible for the temporary breakage, but I'm not sure.

Since the OTP secrets are stored inside of your Yubikey, it's safe to wipe the app and start over from scratch without losing access to all of your logins.

**Comment by rating89us** [comment]
Maybe you should leave this issue open for visibility and because it's not solved.

**Comment by florianajir** [comment]
Having the same issue on oneplus7 but uninstall/reinstall didnt solved the problem for me, didn't tried on other device or with usb otg for now

**Comment by jeantil** [comment]
I have the same issue on my crosscall core-X4 since about a month, I don't use yubi auth very frequently so I am unsure what the exact event was (app update or system update). one week it was working the next it wasn't 

* Uninstall/reinstall of the app from play store didn't restore functionality
* for some reason, I can't install the app through f-droid it says an installed version is incompatible with the availalble version signatures except no version is installed.

**Comment by julienfastre** [comment]
I encoutered the same issue after a first install, using [`/e/`](https://e.foundation/) and Fairphone3+.

Uninstall and reinstall the app solved the problem.

While I encountered the problem, on first install, The phone behaves like the app repeatedly read the NFC data, every one or two seconds. As it would read OTP code instead of OATH data.
