### ISSUE TITLE
Feature request: Time synchronization

### ISSUE THREAD

**Issue by rmenessec** [Yubico/yubioath-android#34]
Google Authenticator (at least as of 4.44) has time correction. This would be useful for people without root access and/or ClockSync installed, not to mention various kinds of local network restrictions. Unknown whether GAuth's facility actually sets the system time, but at minimum it should be able to get the correct time for one-shot TOTP.

SNTP would be appreciated, along with the ability to set one or more NTP servers (default CC.pool.ntp.org ?)

If there isn't already suitable SNTP code available for Android, the simplest method would be to use "HTP" and allow the user to select a server to sync against (default www.google.com?)

"HTP": http://linux.die.net/man/8/htpdate

It would also be great if the app got a bit of a UI overhaul a la GAuth 4.44, but I'd guess that would be a low priority... 😉

**Comment by dainnilsson** [comment]
Regarding UI overhaul, could you be a bit more specific? Looking at GAuth 4.44 it looks strikingly similar, with the biggest change I can see being the use of the light Material theme instead of the dark one. Personally, I prefer the dark one.

**Comment by rmenessec** [comment]
The overall look is a bit cleaner, with nicer UI flow. And, yes, I prefer dark themes. Options for "Light Material" and "Dark Material" would be great. (I know a lot of people who prefer light. If you have time for one new theme, I selfishly prefer "Material Dark".)

**Comment by dainnilsson** [comment]
The current theme IS Material Dark...

**Comment by dainnilsson** [comment]
Anyway, you're going to have to be more specific regarding UI changes. Something concrete, as "nicer UI flow" is very subjective and not easy to interpret. I don't see how this:
![screenshot_20151208-202053](https://cloud.githubusercontent.com/assets/140781/11665829/9fec7d1e-9de9-11e5-9b2e-3d2bc7a593dc.png)

is any improvement over this:

![screenshot_20151208-202048](https://cloud.githubusercontent.com/assets/140781/11665840/acf767f8-9de9-11e5-9318-cad433906401.png)

But obviously I'm biased...

**Comment by Berzerker** [comment]
UI looks fine...

back to the actual task at hand (sorry for hijacking a late thread)

Can the timesync be looked into? Currently it gets out of sync if I tap vs on the Windows app, for example. Would be good if the times were in sync.

**Comment by dainnilsson** [comment]
Are the codes generated on your phone not working? If you're generating codes on the app and they do not match what gets generated on the Windows app, that may instead be due to how this app handles the time differently, see #44 for details on how they differ and why. Because of these differences it is expected that you'll sometimes get different codes if you generate one on the phone, and one on Windows, even if the clocks are perfectly synchronized.

This issue is about synchronizing with a time server, allowing correct codes to be generated on a phone where the clock isn't set properly.

**Comment by Berzerker** [comment]
I haven't actually come across a situation where the codes haven't worked, so I assume your method of design is working as intended, but it just seems like it could create a problem if the app is left for 10-15 seconds before a code is entered. If it becomes a huge problem, I think we can probably revisit it, but I guess it's not an issue for now.

**Comment by bperrybap** [comment]
The issue that can happen is the time that Android is using is off too much.
I have had this issue before. The issue is that if you set the phone to sync with network time, it will only sync with the phone carriers network time. So you can have a situation where there is no network connectivity but there is WIFI and so even though the time could and should have been set using NTP since there is no network time, it isnt since the devices don't/won't use NTP and the time can be off.
In my case if was off a few minutes which was far enough that the tokens would not work.
The only way to resolve this is to change your android device to not use network time sync and set the time manually - assuming you have access to an accurate clock.

Another really good example, is something like the Samsung Galaxy tab tablet.
That device does not have cellular capability AND even worse, does not support using  NTP to set the time.
So time continues to drift and things like authenticator eventually will not work until the time is manually set to be very close to the actual time.

I believe that the Google sync function in their app uses NTP to get the time and uses that time rather than the android time.

So having an internal time sync can be useful since many android implementations of time tracking is so screwed up and won't use NTP to set the system time.

--- bill

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter and we released a new version of the app. We currently don’t plan to add internet connectivity to the app, if this is an issue for you please create a new ticket in the new repo and let’s have a new conversation there.

**Comment by bperrybap** [comment]
Not sure why you closed this. The incorrect time generating invalid tokens is definitely an issue for users. 
i.e. if the time is off because of some sort of device or OS time issue, the app will generate incorrect tokens that will not work.
Yeah it is caused by an issue that is actually outside the app, but the app can work around it without too much difficulty.

IMO, since it is a real-world issue, it should left as a feature request - even if low priority since it can help solve a real-world issue.
For example, add some kind of time sync button to the UI that pings an NTP server to get the time so that the tokens will be correct. It is useful even if the app doesn't or can't set the actual system time on the device.
The app can at least get the correct time to generate the proper tokens.

Think about less technical users. They will have no clue as to why the app is generating incorrect tokens.
They will not know how to fix it and will blame the app.
You guys will get complaints,  bad feedback, and will spend support and or development resources attempting to explain away the issue. The users don't care where the issue is, they just want something that "just works".

It is the little things like this that can change an app from being just good or ok to being great.

**Comment by AdamVe** [comment]
Thanks for a detailed explanation, it is appreciated! 

The issue was closed because the app development has moved to a new codebase at https://github.com/Yubico/yubioath-flutter and will continue there. I will bring your concerns to the team. I have reopened this ticket in https://github.com/Yubico/yubioath-flutter/issues/818
