### ISSUE TITLE
Feature Request: Android Wear Support

### ISSUE THREAD

**Issue by mckaycr** [Yubico/yubioath-android#36]
Google just updated their app with android support, its really cool.  Hoping to see that in yours too since I like your app better.

**Comment by dainnilsson** [comment]
What would the actual feature be? How would you interact with it?

**Comment by mckaycr** [comment]
For Google Authenticator:
Viewing the App on android wear shows you the OTP for an account.  You can
also swipe through each account to see other OTP's, or "open on phone."  It
also displays the count down icon above the OTP.

For Your App
Touching my NEO to my phone would open the app on android wear allowing me
to swipe though all available accounts and seeing their associated OTP

I see the value in this because I don't have to memorize OTP's, race the
clock, while switching between apps on my phone.  I simply initiate the new
OTP with my NEO and view the PIN on my android wear while entering it into
the requesting interface on my phone.

For android wear devices that include NFC, I don't even see the need to
involve the phone at all.

I hope that makes sense.

**Comment by dainnilsson** [comment]
Yeah, that makes sense. I don't believe there is support for NFC in Android Wear as of now, but that might change in the future.

**Comment by unixfox** [comment]
Any news about this feature?

**Comment by dainnilsson** [comment]
No news. The addition of USB support potentially makes this feature more useful/usable as you could potentially have a YubiKey 4C nano attached to your phone and browse and display codes on your watch. There hasn't really been much demand for this, and it sounds like it would require quite a bit of effort. Unfortunately we can't really justify the effort right now.

**Comment by herculeesjr** [comment]
I'm interested in this, but wanted to try explaining a bit more clearly and up to date since the last comment was almost two years ago.
I have an LG Urbane 2 watch, it has NFC built in and runs Android Wear (aka now Wear OS). I'd love to have a Yubico Authenticator app installed on my LG watch so I can just tap my YubiKey on my watch and see my one time codes. No phone involvement or requirement.
The NFC radio is shut off when the screen is off so I suspect the best the implementation could work is I'd have to open the Yubico app on my watch before tapping my YubiKey to the watch, but that's still easy to do and the same amount of steps as using the phone.

**Comment by jzila** [comment]
I just got a new gen 5 Fossil Wear OS watch, and I would love such an app port of yubico authenticator that could let me see my NEO's TOTP codes by simply tapping the watch face when the app is up.

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter and we released a new version of the app. Thank you for the suggestion, we will consider it for development in the new version. Please report any new issues in the new repository.
