### ISSUE TITLE
2.0.0 Bigger Touch Targets?

### ISSUE THREAD

**Issue by edent** [Yubico/yubioath-android#70]
Using the 2 Alpha on Android 7.1.1.

If I tap on the "copy" icon, the code copies successfully to the clipboard.

If I tap slightly under the icon, it doesn't copy.

If I tap on the name of the service, or the code itself, or the coloured icon, it doesn't copy.

Could I suggest that you make the entire row a touch-to-copy target?  That way people with small fingers and big phones won't have to be quite so precise in our clicks.

Thanks :-)

**Comment by dainnilsson** [comment]
I've increased the padding around the buttons, which enlarges the area that is "clickable". I'm a bit hesitant to making the whole row a button since I think it would lead to inadvertent triggering when scrolling or selecting rows. Hope this compromise helps with the issue! If not, feel free to re-open and add further feedback.

**Comment by edent** [comment]
I still find it a bit cumbersome. I appreciate the height shouldn't be any greater - that would make it too easy to accidentally copy the wrong one.

![copy](https://user-images.githubusercontent.com/837136/31853536-e72f359c-b681-11e7-83bf-8448f89444b7.png)

I automatically click on the 6 digit PIN to copy it and at the moment that doesn't work.  So, I would really like the full width to be clickable - but I'd like to know what a bit of usability testing would show.
