### ISSUE TITLE
Confusion about the app

### ISSUE THREAD

**Issue by ervinshiznit** [Yubico/yubioath-android#80]
This isn't an issue with the app (though perhaps an issue with documentation), but I'm not sure where to send these questions otherwise

1. What mode should I configure my Yubikey NEO for? It seems it doesn't require either of the configuration slots to be configured for Yubico OTP, OATH-HOTP, or Challenge-Response mode? I set both slots to static passwords just to try it out, and it works fine. So is it using the U2F mode of my Yubikey then (which doesn't consume a configuration slot)?
2. How exactly does the app store the secrets for the the TOTP accounts I add to this app? Are they stored in plain text somewhere on my phone, and the app merely doesn't generate the 6 digit codes derived from the secrets until I tap my Yubikey? Or are they stored encrypted, and only decrypted when I tap my Yubikey? Or are the secrets stored on the Yubikey itself? That doesn't seem right because when I install the Yubico desktop authenticator app, only one TOTP account shows up (the most recently added one).

**Comment by dagheyman** [comment]
1. Your NEO need to have the USB CCID interface enabled to be used with Yubico Authenticator on desktop.  It's enabled by default on all NEOs sold today, but you can use [YubiKey Manager](https://developers.yubico.com/yubikey-manager-qt/) to double check. On Android, no configuration is needed, it should always work.

2. The secrets are stored on the YubiKey, and can not be exported in any way.

Since this is not a issue with the app, please contact [Yubico Support](https://support.yubico.com/support/tickets/new) for any additional questions.
